import type { Metadata } from "next";
import { Geist, Geist_Mono, Sarabun } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sarabun = Sarabun({
  weight: ['300', '400', '500', '700'], // เลือกความหนาที่จะใช้
  subsets: ['thai', 'latin'], // สำคัญมาก! ต้องใส่ 'thai' เพื่อให้แสดงภาษาไทย
  display: 'swap',
  variable: '--font-sarabun', // ตั้งชื่อตัวแปร CSS เพื่อใช้ใน Tailwind
});

export const metadata: Metadata = {
  title: "e-Phonebook",
  description: "Generated by OAG_ICTC",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,th">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
